name: Deploy to GitHub Pages

on:
  push:
    branches: [main, docs]
    paths: [website/**, .github/workflows/**, sdks/**]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install @switchboard-xyz/common dependencies
        working-directory: javascript/common
        run: |
          yarn install --frozen-lockfile

      - name: Install Aptos SDK dependencies
        working-directory: sdks/aptos
        run: |
          yarn install --frozen-lockfile

      - name: Install Near SDK dependencies
        working-directory: sdks/near/javascript/near.js
        run: |
          yarn install --frozen-lockfile

      - name: Install Solana SDK dependencies
        working-directory: sdks/solana/javascript/solana.js
        run: |
          yarn install --frozen-lockfile

      - name: Install sbv2-lite dependencies
        working-directory: sdks/solana/javascript/sbv2-lite
        run: |
          yarn install --frozen-lockfile

      - name: Install sbv2-utils dependencies
        working-directory: sdks/solana/javascript/sbv2-utils
        run: |
          yarn install --frozen-lockfile

      - name: Build website
        working-directory: website
        run: |
          yarn install --frozen-lockfile
          yarn build:all
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/public
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
