name: Test deployment

on:
  pull_request:
    branches: [main]
    paths: [website/**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: "./website/yarn.lock"
      # - name: Setup npmrc
      #   run:
      #     echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" >
      #     .npmrc
      # - name: Setup yarnrc
      #   run: echo "registry \"https://registry.npmjs.org\"" > .yarnrc
      - name: Test build
        working-directory: website
        run: |
          yarn install
          yarn build
          yarn docgen
